server:
  port: 12000
spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
      routes:
        - id: consumerServer
          uri: lb://consumer-server
          predicates:
            - Path=/cart/getCartById/**
        - id: providerServer
          uri: lb://provider-server
          predicates:
            - Path=/user/getUserById/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: Get, HEAD, POST, PUT, DELETE, OPTIONS
            allowed-headers: "*"
eureka:
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
